language: go
go:
  - 1.7.4

before_install:
  - chmod +x binaries/hugo

install:
  - rm -rf public || exit 0   # cleanup previous run
  - sudo apt-get install tree

script:
  - binaries/hugo -v   # Generate
  - tree -a

deploy:
  provider: s3
  edge: true
  access_key_id:
    secure: "RXqsuyRhGBGI4PkiTooqli3YzvS9U2dZUrFU9IFC5ER9AAFyxwwRU3AiqybRPfiLI9T8iYtftBy35MupJnBUTWfiOldHRFKsnxnGcT1fpph1WS/L6kQ0eiKANIUbQTIMJRzLAEdU34Alxp/FpX1aBNpO/M65zhd/K1aTMlqTTHVDbcZ2rxKr/YQesCiZh3wy/BUaysqOaDlO6jE3JFFkySQu1qeMyV3j+dB0SY9B7G1dwLaKOSGlkC4/+0o7R3r/vS3uhEu5soliUCihk0aYmI9ZXU4AzawZmbDhEY07Tv9gYpsQ+GQzLUAm1hUeMdDv5JrNhni6/iM600hyhcoreiaeXPS9IeuFeAN0aSjQAc+RCpxpICz+esH6RUZlspR0LaxiRx91AeBNZbwEwaWGCm9d40zrLDpuWdY948Kgey+tIgXLkYXc7BMPE+07lZvNL8Ujs8lC2K1lYH5XGs9NxF85m65FfcabT14US9nHNwIazrHG5H/VLGEwcYAxCjMRSSF7bDsnQgqxpAF/WTMSPLTMxpeZbJveMPgbyoGjQQ24cwIj7PVsp+xt13xMoWUxVf2Tajn2j+5EBWdeHdGFF9ixk7fCXJujNA5h7lV2OmxG884ciRghrQTd0lRTfmTmjKmZcgKTuMAqMLlQiNUNQ230Qh5r+IFPWE3NBSTYI8A="
  secret_access_key:
    secure: "Q+p3XuxxOiWPZ0sJqKEXwFGvhVBO9pLzvCbbAXdw79K1V72CgJxg8P7qkRTjWreTF6FLRco/4l9y9ySlxo4ov4vAqEIpiLap086fNGtpwQM5g9x+h4AGA7mNBew+9e/bqZ0B5VHva32+DUpeAfQoaPQiJJiMdi6BnD+SBjwe/OIY6sDAT9NH+noJoWFS6cKwIQ5nZqqhhbgCes9N3BpnKx/RtCryMbmqorOITmErzNWW3Xsx4rQgzLINO6IndJw5jZuZ8aurKzG5mo2ophGV49mfOO0d0vJI+Tc//VvzV8SerrcUmhWORInseHnmoQTmdM286w8pBK2XbDthWqqaVOQysmPxeE/IbueTqYpql0pGfkn4eje42Y033mZz1Hjc4TMWmM7G2aySDnmIz9WxEjUb5pa+V22e1i2MRhUHHHLUS2Sh6wbW+JnwQ8Q1INH38a/TsIezU0sI8j08+0vy7UKDyiunGiPgek5tndsvIRz+khJAX2Z5q8rmcK3g640Sb6N7/bqW5eitE2tryQl+fob28TiUjwRKfmTSEmZrQLYAdguUXUdD3kHAwW5LZbNrkSIWdg65iwvO5Y6w5xRC9EL1yl2ydMVXPtjPiXZqBDQD+e5sc8mtQyHDSQ/hxkMB7bPxj3HD6Q0Waf15HoOgGzvsg9FQ68l8p8V4X4L3Qak="
  bucket: "blogcuistotducoin"
  region: "eu-west-2"
  skip_cleanup: true
  local_dir: public
  upload_dir: public
  acl: public_read
  cache_control: "max-age=21600"
  on:
    branch: master
