backend:
  name: git-gateway
  repo: Cuistotducoin/Blog
  branch: master

publish_mode: editorial_workflow

media_folder: "static/images"
public_folder: "images"

collections:
  - name: "Articles"
    label: "Articles"
    folder: "content/post"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields: # The fields for each document, usually in front matter
      - {label: "Titre", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Cover Image", name: "image", widget: "image", required: false, tagname: ""}
      - {label: "Categories", name: "categories", widget: "list"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Texte", name: "body", widget: "markdown"}
