backend:
  name: github
  repo: JeresB/Blog-Cuistot-du-coin
  branch: master

publish_mode: editorial_workflow

media_folder: "/images"

collections:
  - name: "Articles"
    label: "Articles"
    folder: "content/post"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields: # The fields for each document, usually in front matter
      - {label: "Titre", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Texte", name: "body", widget: "markdown"}
    meta:
      - {label: "Date", name: "date", widget: "datetime"}
